import Head from "next/head";

import { Inter } from "next/font/google";
import NoveCard from "@/components/NoveCard";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-[90%] m-auto ">
        <h1 className="text-3xl font-bold underline">hola next js</h1>
        <h1 className="text-primary-color">Hola soy Marcos</h1>
        <div className="flex justify-around flex-wrap">
          <NoveCard />
          <NoveCard />
          <NoveCard />
          <Navbar />
        </div>
      </main>
    </>
  );
}
