import Head from "next/head";

import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";
import Testimonios from "@/components/Testimonios";
import SliderMoveCard from "@/components/SliderMoveCard";
import SliderDestacCard from "@/components/SliderDestacCard";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/73d94b16ae.js"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <Navbar />
      <main className="w-[90%] m-auto ">
        <div className="flex justify-around flex-wrap">
          <Banner />
        </div>
        <div className="relative">
          <h2 className="font-bold text-4xl text-text font-Kanit my-4">
            NOVEDADES
          </h2>
          <SliderMoveCard />
        </div>
        <div className="relative">
          <h2 className="font-bold text-4xl text-text font-Kanit my-4">
            PROYECTOS DESTACADOS
          </h2>
          <SliderDestacCard />
        </div>
      </main>
      <Footer />
    </>
  );
}
